In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import os
os.chdir('/content/drive/MyDrive/BigContest_JSH/BigContest/지수현')

import dask.dataframe as dd
import time
import pandas as pd

import matplotlib.pyplot as plt
import numpy as np

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df=pd.read_csv('transit_columns3.csv')
df

,구분,max_time,min_time,num_trainsit_methods,median_time,예상 배차시간,최대 이동거리,최소 이동거리,이동거리 중간값,최대 교통수단 수,환승횟수,마지막 도보시간 중간값,마지막 도보시간 평균
0,BB,5413,2758,2,3066.0,287.931818,25962,13040,13699,3,3.013699,3.300000,8.600000
1,BD,14581,7437,4,8565.0,195.618421,211083,207278,209009,3,4.298507,4.150000,5.050000
2,BGA,23378,2471,5,22828.0,331.551724,308473,299594,303565,3,5.165605,2.333333,17.250000
3,BGB,24011,2511,5,22093.0,193.017241,311981,30419,304010,3,5.165605,2.333333,5.200000
4,BI,21593,16229,5,18940.0,290.399015,262567,230051,256362,4,5.705405,3.783333,21.733333
5,BS,23197,11864,3,16002.5,286.430769,338414,33448,335721,3,3.867257,4.550000,3.650000
6,DD,4145,1958,2,2387.0,210.227273,15483,8619,10085,2,2.958904,3.841667,5.050000
7,GGA,2488,1904,2,2215.0,442.641509,5725,3754,4508,1,2.965909,3.100000,17.250000
8,GGB,6124,1844,3,2155.0,223.325581,31749,7262,7296,2,3.037209,3.100000,4.083333
9,II,185,107,2,265.0,218.333333,347738,115,13547,1,3.000000,1.966667,7.883333
10,SB,23487,9803,4,20332.0,276.149733,369479,340827,340841,4,4.082317,5.050000,10.066667
11,SD,11411,6467,3,9568.0,205.338710,154480,150675,152219,3,4.201835,4.150000,4.150000
12,SGA,204386,8160,3,11640.0,696.526316,220586,191468,204386,3,3.305556,4.000000,29.000000
13,SGB,16968,9004,5,13121.5,211.992126,206356,177862,182214,4,5.861171,3.983333,4.083333
14,SI,17010,9309,4,14428.0,481.507433,226695,216432,221938,3,3.318584,4.383333,7.883333
15,SS,2578,1542,2,1717.0,199.423729,10875,6202,6775,2,2.969388,3.650000,5.150000

In [ ]:
df_time = (df['max_time'] - df['median_time']) / (df['max_time'] - df['min_time'])
df_time

0     0.883992
1     0.842105
2     0.026307
3     0.089209
4     0.494594
5     0.634827
6     0.803841
7     0.467466
8     0.927336
9    -1.025641
10    0.230561
11    0.372775
12    0.982265
13    0.482986
14    0.335281
15    0.831081
dtype: float64

In [ ]:
df_distance = (df['최대 이동거리'] - df['이동거리 중간값']) / (df['최대 이동거리'] - df['최소 이동거리'])
df_distance

0     0.949002
1     0.545072
2     0.552765
3     0.028310
4     0.190829
5     0.008830
6     0.786422
7     0.617453
8     0.998612
9     0.961360
10    0.999511
11    0.594218
12    0.556357
13    0.847266
14    0.463510
15    0.877381
dtype: float64

In [ ]:
df_change=(df['max_time'] - df['min_time']) / (df['max_time'] - (df['예상 배차시간'] + (df['환승횟수'] * df['예상 배차시간'])))
df_change

0     0.623631
1     0.527446
2     0.979995
3     0.942118
4     0.273036
5     0.519794
6     0.660180
7     0.797243
8     0.819548
9    -0.113317
10    0.619648
11    0.478011
12    0.974372
13    0.513360
14    0.515787
15    0.579934
dtype: float64

In [ ]:
df_transit=(df['최대 교통수단 수']/df['num_trainsit_methods'])
df_transit

0     1.500000
1     0.750000
2     0.600000
3     0.600000
4     0.800000
5     1.000000
6     1.000000
7     0.500000
8     0.666667
9     0.500000
10    1.000000
11    1.000000
12    1.000000
13    0.800000
14    0.750000
15    1.000000
dtype: float64

In [ ]:
# 가중치 설정
w_distance = 0.4        #거리 접근성 가중치
w_time = 0.3    # 시간 접근성 가중치
w_환승 = 0.2        # 환승 접근성 가중치
w_교통수단 = 0.1    # 교통수단 접근성 가중치

In [ ]:
df_composite = (
    w_time * df_time +
    w_distance * df_distance +
    w_환승 * df_change +
    w_교통수단 * df_transit
)

In [ ]:
df_composite

0     0.919525
1     0.651150
2     0.484997
3     0.286510
4     0.359317
5     0.397939
6     0.787757
7     0.596670
8     0.908222
9     0.104188
10    0.692902
11    0.545122
12    0.812097
13    0.666474
14    0.464146
15    0.816263
dtype: float64

In [ ]:
df_composite.nlargest(5)

0     0.919525
8     0.908222
15    0.816263
12    0.812097
6     0.787757
dtype: float64